import type { CaptionStyle, StylePreset } from './types'

const base: CaptionStyle = {
  fontFamily: 'Inter, sans-serif',
  fontWeight: 800,
  fontSize: 0.062,
  textColor: '#ffffff',
  activeColor: '#ffe600',
  highlightColor: '#7c3aed',
  strokeColor: '#000000',
  strokeWidth: 0.12,
  backgroundColor: 'rgba(0,0,0,0)',
  backgroundMode: 'line',
  backgroundPadding: 0.012,
  backgroundRadius: 0.02,
  position: 'center',
  marginY: 0.5,
  textTransform: 'uppercase',
  letterSpacing: 0,
  lineHeight: 1.15,
  maxWordsPerCue: 4,
  activeWordEffect: 'color',
  entrance: 'pop',
  shadowBlur: 0.04,
  shadowColor: 'rgba(0,0,0,0.55)',
  emojiBoost: true,
}

export const PRESETS: StylePreset[] = [
  {
    id: 'hormozi',
    name: 'Viral Pop',
    description: 'Bold all-caps captions with a bright active word for punchy hooks.',
    style: {
      ...base,
      fontWeight: 900,
      fontSize: 0.07,
      activeColor: '#ffe600',
      activeWordEffect: 'color',
      strokeWidth: 0.14,
      entrance: 'pop',
      maxWordsPerCue: 3,
    },
  },
  {
    id: 'premiere',
    name: 'Creator Pro',
    description:
      'Broadcast-grade captions in a translucent box with a subtle spoken-word reveal.',
    style: {
      ...base,
      fontFamily: 'Inter, sans-serif',
      fontWeight: 700,
      fontSize: 0.044,
      textColor: '#ffffff',
      activeColor: '#ffffff',
      textTransform: 'none',
      activeWordEffect: 'reveal',
      entrance: 'fade',
      strokeWidth: 0,
      backgroundColor: 'rgba(15,16,22,0.82)',
      backgroundMode: 'block',
      backgroundPadding: 0.02,
      backgroundRadius: 0.016,
      position: 'bottom',
      marginY: 0.11,
      lineHeight: 1.32,
      letterSpacing: 0.004,
      maxWordsPerCue: 7,
      shadowBlur: 0.015,
      shadowColor: 'rgba(0,0,0,0.5)',
    },
  },
  {
    id: 'editorial',
    name: 'Editorial',
    description:
      'Minimal, no box: crisp white text with a soft shadow and a tasteful accent on the spoken word.',
    style: {
      ...base,
      fontFamily: 'Inter, sans-serif',
      fontWeight: 700,
      fontSize: 0.05,
      textColor: '#f8fafc',
      activeColor: '#5b9dff',
      textTransform: 'none',
      activeWordEffect: 'color',
      entrance: 'slide-up',
      strokeWidth: 0,
      backgroundColor: 'rgba(0,0,0,0)',
      backgroundMode: 'none',
      position: 'bottom',
      marginY: 0.13,
      lineHeight: 1.22,
      maxWordsPerCue: 5,
      shadowBlur: 0.05,
      shadowColor: 'rgba(0,0,0,0.65)',
    },
  },
  {
    id: 'karaoke',
    name: 'Karaoke',
    description: 'Each word lights up with a colored box as it is spoken.',
    style: {
      ...base,
      fontWeight: 800,
      fontSize: 0.058,
      textColor: '#ffffff',
      highlightColor: '#ec4899',
      activeWordEffect: 'highlight',
      entrance: 'fade',
      strokeWidth: 0.08,
      maxWordsPerCue: 5,
    },
  },
  {
    id: 'tiktok',
    name: 'Clean Social',
    description: 'Minimal white text on a subtle dark pill for everyday posts.',
    style: {
      ...base,
      fontWeight: 700,
      fontSize: 0.05,
      textTransform: 'none',
      activeWordEffect: 'none',
      strokeWidth: 0,
      backgroundColor: 'rgba(0,0,0,0.55)',
      backgroundPadding: 0.018,
      backgroundRadius: 0.03,
      entrance: 'slide-up',
      shadowBlur: 0,
      position: 'bottom',
      marginY: 0.12,
      maxWordsPerCue: 6,
    },
  },
  {
    id: 'pop',
    name: 'Bounce',
    description: 'Words pop in one by one while the active word scales up.',
    style: {
      ...base,
      fontWeight: 900,
      fontSize: 0.066,
      activeColor: '#22d3ee',
      activeWordEffect: 'scale',
      entrance: 'word-by-word',
      strokeWidth: 0.12,
      maxWordsPerCue: 4,
    },
  },
  {
    id: 'neon',
    name: 'Neon Night',
    description: 'Glowing neon text with a soft shadow for dark, high-energy clips.',
    style: {
      ...base,
      fontWeight: 800,
      fontSize: 0.06,
      textColor: '#f5f3ff',
      activeColor: '#a855f7',
      activeWordEffect: 'color',
      strokeColor: '#4c1d95',
      strokeWidth: 0.06,
      shadowBlur: 0.12,
      shadowColor: 'rgba(168,85,247,0.9)',
      entrance: 'fade',
      maxWordsPerCue: 4,
    },
  },
  {
    id: 'subtitle',
    name: 'Classic',
    description: 'Traditional bottom subtitles with one readable line at a time.',
    style: {
      ...base,
      fontWeight: 600,
      fontSize: 0.044,
      textTransform: 'none',
      activeWordEffect: 'none',
      strokeColor: '#000000',
      strokeWidth: 0.1,
      entrance: 'none',
      position: 'bottom',
      marginY: 0.08,
      maxWordsPerCue: 8,
      shadowBlur: 0.02,
    },
  },
]

export const DEFAULT_STYLE: CaptionStyle = { ...PRESETS[0].style }

export const FONT_OPTIONS = [
  { label: 'Inter', value: 'Inter, sans-serif' },
  { label: 'Arial Black', value: '"Arial Black", Arial, sans-serif' },
  { label: 'Impact', value: 'Impact, "Arial Narrow Bold", sans-serif' },
  { label: 'Georgia', value: 'Georgia, serif' },
  { label: 'Courier', value: '"Courier New", monospace' },
  { label: 'Verdana', value: 'Verdana, Geneva, sans-serif' },
  { label: 'Trebuchet', value: '"Trebuchet MS", sans-serif' },
]
